### ISSUE TITLE
Testing Checklist

### ISSUE THREAD

**Issue by carsonharmon** [trailofbits/polytracker#6340]
We should add tests for the following things

- [ ]  DFSan/Polytracker coupling test 
- [ ]  Control flow graph collection/generation test
- [ ]  More C++ tests with different parts of the standard library
- [ ]  Determinism tests 
- [ ]  Profiling tests
