### ISSUE TITLE
Refactoring TODO list

### ISSUE THREAD

**Issue by carsonharmon** [trailofbits/polytracker#99]
- [x] Change numTraceEvents to an std::atomic
- [x] Make eventIndex const 
- [ ] Add CPP check to CI for taint manager 
- [x] Polytracker trace is global but doesn't need to be, either have the global or not 
- [x] Add inline static to the recordTrace prefix if not doing the thing above 
- [x] Check to see if we can remove the taint mapping lock, do we ever do mapping with locking the mono lock?
- [x] Mark forest mem as const and use initializer list syntax to set it. 
- [x] getTaintNode defined as inline within the class body 
- [x] log mgmt func stack makes a copy, change things around to use references instead. 
- [x] Remove init logic check from func entry/bb entry because we should be init because of the pre_init_array right?
- [x] In general, look for copying and try to avoid it. 
- [x] Remove the taint manager class 
- [x] Divorce polytracker pass from DFSan pass
